spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE}
  application:
    name: bff-notes

server:
  port: 9004
  servlet:
    context-path: /bff-notes

management:
  server:
    port: 9192
  endpoints:
    web:
      exposure:
        include: info, health, metrics, loggers, monitoring, prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.saveit: ${LOGGING_LEVEL_APP:ERROR}
    org.springframework: ${LOGGING_LEVEL_SPRING:ERROR}

saveit:
  notes-service:
    url: ${NOTES_SERVICE_URL}