apiVersion: v1
kind: ConfigMap
metadata:
  namespace: notes-app
  name: bff-notes-config
data:
  SPRING_PROFILE_ACTIVE: "dev"
  LOGGING_LEVEL_APP: "DEBUG"
  LOGGING_LEVEL_SPRING: "DEBUG"
  NOTES_SERVICE_URL: http://notes-service.notes-app.svc.cluster.local:9004